function create1942(X1, ymatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  area x
%  YMATRIX1:  area matrix data

%  Auto-generated by MATLAB on 17-Jul-2014 15:38:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTick',[0 600 1200 1800 2400 3000 3600 4200 4800 5400 6000 6569.687]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 6569.687]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

% Create title
title('Area Chart of Answer Types for Event 1 (1942 Data Points)');

% Create multiple lines using matrix input to area
area1 = area(X1,ymatrix1,'Parent',axes1);
set(area1(1),'DisplayName','ID');
set(area1(2),'FaceColor',[0 1 0],'DisplayName','IC');
set(area1(3),'FaceColor',[1 1 0],'DisplayName','CD');
set(area1(4),'FaceColor',[1 0 0],'DisplayName','CC');

% Create xlabel
xlabel('Time Passed (s)');

% Create ylabel
ylabel('Percent');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast','YDir','reverse');

