function createdisthist(VertexNormals1, YData1, XData1, Vertices1, Faces1, FaceVertexCData1, CData1)
%CREATEFIGURE1(VERTEXNORMALS1,YDATA1,XDATA1,VERTICES1,FACES1,FACEVERTEXCDATA1,CDATA1)
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  CDATA1:  patch cdata

%  Auto-generated by MATLAB on 16-Jul-2014 13:07:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'CLim',[1 2]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1500]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 200]);
box(axes1,'on');

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor','flat',...
    'EdgeColor','flat',...
    'FaceVertexCData',FaceVertexCData1,...
    'DisplayName','dist',...
    'CData',CData1);

% Create xlabel
xlabel('Distance (m)');

% Create ylabel
ylabel('Count');

% Create title
title('Distances from Answer Locations');

