function createfigure1(X1, ymatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  area x
%  YMATRIX1:  area matrix data

%  Auto-generated by MATLAB on 15-Jul-2014 17:36:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

xlim(axes1,[0,7694.687]);

% Create title
title('Area Chart of Answer Types');

% Create multiple lines using matrix input to area
area1 = area(X1,ymatrix1,'Parent',axes1);
set(area1(1),...
    'FaceColor',[0.0784313753247261 0.168627455830574 0.549019634723663],...
    'DisplayName','CC');
set(area1(2),'FaceColor',[0 0.498039215803146 0],'DisplayName','CD');
set(area1(3),'DisplayName','IC');
set(area1(4),'DisplayName','ID');

% Create xlabel
xlabel('Time Passed (s)');

% Create ylabel
ylabel('Percent');

% Create legend
legend(axes1,'show');

