function createAreaDist(X1, ymatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  area x
%  YMATRIX1:  area matrix data

%  Auto-generated by MATLAB on 05-Aug-2014 17:22:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'60','100','200','300','400','500','600','700','800','900','1,000','1,100','1,200'},...
    'XTick',[60 100 200 300 400 500 600 700 800 900 1000 1100 1200],...
    'XMinorTick','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[5.10715988714121 1200]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to area
area1 = area(X1,ymatrix1,'Parent',axes1);
set(area1(1),'DisplayName','ID');
set(area1(2),'FaceColor',[0 1 0],'DisplayName','IC');
set(area1(3),'FaceColor',[1 1 0],'DisplayName','CD');
set(area1(4),'FaceColor',[1 0 0],'DisplayName','CC');

% Create xlabel
xlabel('Distance from Current Question (m)');

% Create ylabel
ylabel('Percent');

% Create title
title('Area Chart of Answer Types vs Current Location for Event 1');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','East','YDir','reverse');

