function createfigure1(X1, Y1, S1, C1, X2, YMatrix1, X3, Y2, C2, X4, Y3, X5, Y4)
%CREATEFIGURE1(X1, Y1, S1, C1, X2, YMATRIX1, X3, Y2, C2, X4, Y3, X5, Y4)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  X3:  scatter x
%  Y2:  scatter y
%  C2:  scatter c
%  X4:  scatter x
%  Y3:  scatter y
%  X5:  scatter x
%  Y4:  scatter y

%  Auto-generated by MATLAB on 06-Aug-2014 14:32:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 12000]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1200]);
hold(axes1,'all');

% Create scatter
scatter(X1,Y1,S1,C1,'MarkerFaceColor',[0 0 1],...
    'MarkerEdgeColor',[0 0.447058826684952 0.74117648601532],...
    'Marker','square',...
    'Parent',axes1,...
    'DisplayName','CC');

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','CC polyfit');
set(plot1(2),'Color',[0 1 0],'DisplayName','CD polyfit');
set(plot1(3),'Color',[1 1 0],'DisplayName','IC polyfit');
set(plot1(4),'Color',[1 0 0],'DisplayName','ID polyfit');

% Create scatter
scatter(X3,Y2,S1,C2,'MarkerFaceColor',[0 1 0],...
    'MarkerEdgeColor',[0 0.498039215803146 0],...
    'Parent',axes1,...
    'DisplayName','CD');

% Create scatter
scatter(X4,Y3,S1,C2,'MarkerFaceColor',[1 1 0],...
    'MarkerEdgeColor',[1 0.843137264251709 0],...
    'Marker','pentagram',...
    'Parent',axes1,...
    'DisplayName','IC');

% Create scatter
scatter(X5,Y4,S1,C2,'MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'Parent',axes1,...
    'DisplayName','ID');

% Create title
title('Scatter Plot of Answer Types on Time vs Distance n=1');

% Create xlabel
xlabel('Time (s)');

% Create ylabel
ylabel('Distance (m)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','Best');

