function create1942(X1, ymatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  area x
%  YMATRIX1:  area matrix data

%  Auto-generated by MATLAB on 16-Jul-2014 13:50:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 6569.687]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

% Create title
title('Area Chart of Answer Types for Event 1 (1942 Data Points)');

% Create multiple lines using matrix input to area
area1 = area(X1,ymatrix1,'Parent',axes1);
lh = legend('ID','IC','CD','CC');
set(lh,'ydir','reverse');
set(area1(1),'DisplayName','CC');
set(area1(2),'FaceColor',[0 1 0],'DisplayName','CD');
set(area1(3),'FaceColor',[1 1 0],'DisplayName','IC');
set(area1(4),'FaceColor',[1 0 0],'DisplayName','ID');

% Create xlabel
xlabel('Time Passed (s)');

% Create ylabel
ylabel('Percent');

% Create legend
legend(axes1,'show');

